apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: solanawatchx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-exempt: "127.0.0.1"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/websocket-services: "analytics-api"
spec:
  tls:
    - hosts:
        - solanawatchx.site
      secretName: solanawatchx-tls
  rules:
    - host: solanawatchx.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: analytics-api
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: analytics-api
                port:
                  number: 8000
